-- MySQL Script generated by MySQL Workbench
-- Sun Jan  3 19:22:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `Onoma` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tilefono` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Akinito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Akinito` (
  `idAkinito` INT NOT NULL AUTO_INCREMENT,
  `price` INT NOT NULL,
  `register_date` DATE NOT NULL,
  `refresh_date` DATE NOT NULL,
  `size` DECIMAL(2) NOT NULL,
  `Area` VARCHAR(45) NOT NULL,
  `Sale_Rent` BINARY(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idAkinito`),
  UNIQUE INDEX `idAkinito_UNIQUE` (`idAkinito` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kataxorei`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kataxorei` (
  `idUser` INT NOT NULL,
  `IdAkinito` INT NOT NULL,
  PRIMARY KEY (`idUser`, `IdAkinito`),
  INDEX `agelia_idx` (`IdAkinito` ASC) ,
  CONSTRAINT `xristis`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `agelia`
    FOREIGN KEY (`IdAkinito`)
    REFERENCES `mydb`.`Akinito` (`idAkinito`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Search`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Search` (
  `idxristis` INT NOT NULL,
  `idaggelia` INT NOT NULL,
  PRIMARY KEY (`idxristis`, `idaggelia`),
  INDEX `idaggelias_idx` (`idaggelia` ASC) ,
  CONSTRAINT `idaggelias_Search`
    FOREIGN KEY (`idaggelia`)
    REFERENCES `mydb`.`Akinito` (`idAkinito`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idxristi_Search`
    FOREIGN KEY (`idxristis`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Save`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Save` (
  `idXristi` INT NOT NULL,
  `IdAggelia` INT NOT NULL,
  PRIMARY KEY (`idXristi`, `IdAggelia`),
  INDEX `idAggelia_idx` (`IdAggelia` ASC) ,
  CONSTRAINT `idXristi_save`
    FOREIGN KEY (`idXristi`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idAggelia_save`
    FOREIGN KEY (`IdAggelia`)
    REFERENCES `mydb`.`Akinito` (`idAkinito`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hide`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hide` (
  `idXristi` INT NOT NULL,
  `IdAggelia` INT NOT NULL,
  PRIMARY KEY (`idXristi`, `IdAggelia`),
  INDEX `IdAggelia_hide_idx` (`IdAggelia` ASC) ,
  CONSTRAINT `IdXristi_Hide`
    FOREIGN KEY (`idXristi`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `IdAggelia_hide`
    FOREIGN KEY (`IdAggelia`)
    REFERENCES `mydb`.`Akinito` (`idAkinito`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Home`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Home` (
  `idHome` INT NOT NULL,
  `Ypokatigoria` VARCHAR(45) NOT NULL,
  `Ypnodomatia` INT NOT NULL,
  `Orofos` INT NOT NULL,
  `Etos kataskeuis` INT NOT NULL,
  `Epipla` BINARY(1) NOT NULL DEFAULT 0,
  `Parking` BINARY(1) NOT NULL DEFAULT 0,
  `Apothiki` BINARY(1) NOT NULL DEFAULT 0,
  `Verada` BINARY(1) NOT NULL DEFAULT 0,
  `Porta_Asfalias` BINARY(1) NOT NULL DEFAULT 0,
  `Klimatismos` BINARY(1) NOT NULL DEFAULT 0,
  `Sinagermos` BINARY(1) NOT NULL DEFAULT 0,
  `Tzaki` BINARY(1) NOT NULL DEFAULT 0,
  `Elevator` BINARY(1) NOT NULL DEFAULT 0,
  `View` BINARY(1) NOT NULL DEFAULT 0,
  `Garden` BINARY(1) NOT NULL DEFAULT 0,
  `Pool` BINARY(1) NOT NULL DEFAULT 0,
  `Retire` BINARY(1) NOT NULL DEFAULT 0,
  `Sun_Heater` BINARY(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idHome`),
  UNIQUE INDEX `idHome_UNIQUE` (`idHome` ASC) ,
  CONSTRAINT `IdAggelia_Home`
    FOREIGN KEY (`idHome`)
    REFERENCES `mydb`.`Akinito` (`idAkinito`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Office` (
  `idOffice` INT NOT NULL,
  `Ypokatoigodia` VARCHAR(45) NOT NULL,
  `Domatia` INT NOT NULL,
  `Orofos` INT NOT NULL,
  `Etos_kataskeuis` INT NOT NULL,
  `Parking` BINARY(1) NOT NULL DEFAULT 0,
  `Apothiki` BINARY(1) NOT NULL DEFAULT 0,
  `Porta_asfalias` BINARY(1) NOT NULL DEFAULT 0,
  `Klmatismos` BINARY(1) NOT NULL DEFAULT 0,
  `Sinagermos` BINARY(1) NOT NULL DEFAULT 0,
  `Elevator` BINARY(1) NOT NULL DEFAULT 0,
  `Retire` BINARY(1) NOT NULL DEFAULT 0,
  `Corner` BINARY(1) NOT NULL DEFAULT 0,
  `Ramp_Load` BINARY(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idOffice`),
  UNIQUE INDEX `idOffice_UNIQUE` (`idOffice` ASC) ,
  CONSTRAINT `Id_Aggelia_Office`
    FOREIGN KEY (`idOffice`)
    REFERENCES `mydb`.`Akinito` (`idAkinito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Land`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Land` (
  `idLand` INT NOT NULL,
  `Ypokatoigoria` VARCHAR(45) NOT NULL,
  `Corner` BINARY(1) NOT NULL DEFAULT 0,
  `Oikistiki_Zoni` BINARY(1) NOT NULL DEFAULT 0,
  `Entos_Sxediou` BINARY(1) NOT NULL DEFAULT 0,
  `Prosopsis` BINARY(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idLand`),
  UNIQUE INDEX `idLand_UNIQUE` (`idLand` ASC) ,
  CONSTRAINT `idAggelia_Land`
    FOREIGN KEY (`idLand`)
    REFERENCES `mydb`.`Akinito` (`idAkinito`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
